name: CastleSiege
main: me.cbhud.castlesiege.CastleSiege
author: cbhud
version: 1.3.4
api-version: 1.17
commands:
  cs:
    description: Castle Siege main command
    usage: /<command> <setlobby|teamspawn|setkingspawn|start|endgame|type|save>
    permission: cs.admin
  stats:
    description: Check player stats
    usage: /stats [player]
  coins:
    description: Manage player coins.
    usage: /coins <set|add|remove> <player> <amount>
    permission: cs.admin
    permission-message: You do not have permission to use this command.
  kit:
    description: Manage player kits.
    usage: /kit <lock|unlock> <kit> <player>
    permission: cs.admin
    permission-message: You do not have permission to use this command.
